//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GRCWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalRecord
    {
        public int PersonId { get; set; }
        public int EventId { get; set; }
        public System.TimeSpan Time { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string RaceName { get; set; }
        public bool GRC { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Person Person { get; set; }
    }
}
